name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ZIP component directory
        run: |
          cd ${{ github.workspace }}/custom_components/evse_load_balancer
          zip evse_load_balancer.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/evse_load_balancer/evse_load_balancer.zip
          asset_name: evse_load_balancer.zip
          tag: ${{ github.ref }}
          overwrite: true
